#!/usr/bin/env python3
"""make_report.py -- assemble MIGRATION_REPORT.md from the JSON produced by the other steps.

    make_report.py --paper MyPaper --src-venue aaai2027 --dst-venue iclr2027 --stage submission \
                   --verify verify.json --rules rules.json --body-diff body_diff.json \
                   --layout layout.json --compile compile.json --compliance compliance.json \
                   --deliverable "~/Desktop/paper_iclr2027.zip" --deliverable "~/Desktop/paper_iclr2027/" \
                   [--preexisting "text"]... [--note "text"]... --out MIGRATION_REPORT.md

The report opens with an *Author to-do* list (things only the authors can decide), then the
evidence section by section.  Missing inputs are reported as "not run".  Standard library only.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from verify_template import load_manifest  # noqa: E402


def load(path: str | None) -> dict | None:
    if not path or not Path(path).is_file():
        return None
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def fmt_frac(x) -> str:
    try:
        return f"{float(x):.2f}".rstrip("0").rstrip(".")
    except (TypeError, ValueError):
        return str(x)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--paper", required=True)
    ap.add_argument("--src-venue", required=True)
    ap.add_argument("--dst-venue", required=True)
    ap.add_argument("--stage", default="submission")
    ap.add_argument("--manifest", default=str(Path(__file__).resolve().parent.parent / "venues.yaml"))
    for k in ("verify", "rules", "body_diff", "layout", "compile", "compliance"):
        ap.add_argument("--" + k.replace("_", "-"))
    ap.add_argument("--deliverable", action="append", default=[])
    ap.add_argument("--preexisting", action="append", default=[], help="pre-existing issue found in the source (repeatable)")
    ap.add_argument("--note", action="append", default=[], help="extra line for the 'Not done / notes' section")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    man = load_manifest(Path(args.manifest))
    sv, dv = man["venues"].get(args.src_venue, {}), man["venues"].get(args.dst_venue, {})
    sname, dname = sv.get("name", args.src_venue), dv.get("name", args.dst_venue)
    V, R, B, L, C, K = (load(getattr(args, k)) for k in ("verify", "rules", "body_diff", "layout", "compile", "compliance"))
    today = dt.date.today().isoformat()
    out: list[str] = []
    P = out.append

    P(f"# Migration report: {args.paper}, {sname} -> {dname} ({args.stage.replace('_', '-')})")
    P("")
    P(f"Generated by paper-migrate on {today}. The source project was not modified. Only formatting was changed; "
      "the content-invariance check below is the proof. Everything listed under *Author to-do* is a decision the tool does not make.")
    P("")

    # ---------------- author to-do -------------------------------------------
    P("## Author to-do")
    n = 0
    if K:
        for c in K["checks"]:
            if c["status"] == "author action":
                n += 1
                P(f"{n}. **{c['rule']}.** {c['detail']}" + (f" _Source: {c['source']}_" if c.get("source") else ""))
    if L:
        bits = []
        for w in L.get("wraps", []):
            if w.get("status") == "wrapped":
                bits.append(f"`{w['label']}` wrapped by text ({w['env']}, {fmt_frac(w['frac'])} of the line)")
        for p in L.get("pairs", []):
            if p.get("status") == "paired":
                bits.append(f"{' + '.join('`' + x + '`' for x in p.get('items', p['labels']))} combined into one {p.get('env', 'float')} with (a)/(b) sub-captions; `\\ref` now renders e.g. 3a" if p.get("mode") == "subfloats"
                            else f"{' + '.join('`' + x + '`' for x in p.get('items', p['labels']))} placed side by side")
        for r in L.get("rows", []):
            if "enlarged" in str(r.get("action", "")):
                bits.append(f"`{r['file']}` enlarged ({r['action'].split('(enlarged')[1].split(';')[0].strip(' )')})")
            if "capped" in str(r.get("action", "")):
                bits.append(f"`{r['file']}` capped at the text width")
        tc = L.get("table_captions") or {}
        if tc.get("moved"):
            bits.append(f"{tc['moved']} table caption(s) moved {tc['where']} their tables (venue rule)")
        if bits:
            n += 1
            P(f"{n}. **Layout to eyeball** (all reversible; details in the Layout section): " + "; ".join(bits) + ".")
        refused = [w for w in L.get("wraps", []) if w.get("status") == "refused"]
        if refused:
            n += 1
            P(f"{n}. **Not wrapped on purpose:** " + "; ".join(f"`{w['label']}` ({w.get('reason', '')})" for w in refused) + ".")
    if K:
        for c in K["checks"]:
            if c["status"] == "info" and c["rule"] in ("main-text page limit", "references position"):
                n += 1
                P(f"{n}. **{c['rule']}.** {c['detail']}")
    if n == 0:
        P("Nothing requires the authors' attention beyond a read-through of the compiled PDF.")
    P("")

    # ---------------- template -------------------------------------------------
    P("## Template")
    if V:
        okf = sum(1 for f in V.get("files", []) if f["status"] == "match")
        P(f"`verify_template.py --venue {args.dst_venue}` -> {'PASS' if V.get('passed') else 'FAIL'}: {okf}/{len(V.get('files', []))} files match the SHA-256 values in `venues.yaml`"
          + (f" (official zip verified {dv.get('official', {}).get('verified_on')})" if dv.get('official', {}).get('verified_on') else "") + ".")
    else:
        P("verify_template: not run.")
    P("")

    # ---------------- content invariance ---------------------------------------
    P("## Content invariance (body_diff)")
    if B:
        h = B["hunks"]
        P(f"`RESULT: {'PASS' if B.get('passed') else 'FAIL'}` -- tokens {B['tokens']['src']} -> {B['tokens']['dst']}; hunks: format {h['format']}, structure {h['structure']}, **content {h['content']}**.")
        ck = B["checks"]
        P("")
        P("| Check | Result |")
        P("|---|---|")
        P(f"| Title | {'identical' if ck['title']['ok'] else 'DIFFERS'} |")
        a = ck["authors"]
        P(f"| Author / affiliation / e-mail text | {a['src_words']} words and {a['src_emails']} e-mails from the source; missing: {a['missing_words'] + a['missing_emails'] or 'none'} |")
        mm = ck["macros"]
        P(f"| Macros / environments used by the body | missing: {mm['missing_used_in_dst'] or 'none'}; collisions: {mm['collisions_with_inputs'] or 'none'} |")
        c = ck["citations"]
        P(f"| Citation keys / uses | {c['src']}/{c['dst']} keys, {c['src_uses']}/{c['dst_uses']} uses; missing {c['missing'] or 'none'} |")
        P(f"| Labels / refs | {ck['labels']['src']}/{ck['labels']['dst']}, {ck['refs']['src']}/{ck['refs']['dst']}; dangling {ck['refs']['dangling_in_dst'] or 'none'} |")
        P(f"| Section headings ({ck['headings']['src']}) | {'identical' if ck['headings']['ok'] else 'DIFFER'} |")
        P(f"| Bibliography files | {[(r['name'], 'equal' if r.get('equal') else 'CHANGED') for r in ck['bib_files']]} |")
        fg = ck["figure_files"]
        P(f"| Figure files | {len(fg)} referenced, {sum(1 for r in fg if r.get('equal'))} byte-identical |")
        P("")
        fc = B.get("format_changes") or {}
        if fc:
            P("Format changes (whitelisted): " + ", ".join(f"`{k}`x{v}" for k, v in list(fc.items())[:16]) + ".")
        sf = B.get("starred_floats") or {}
        if sf.get("src"):
            P(f"Starred floats normalised: {sf['src']} -> {sf.get('dst') or '{}'}.")
        st = B.get("hunk_details", {}).get("structure", [])
        if st:
            P("")
            P("Structure hunks (reviewed):")
            for s in st:
                P(f"- src L{s['src_line']} -> dst L{s['dst_line']}: {s.get('note') or 'environment change'}; `{s['removed'][:70]}` -> `{s['added'][:70]}`")
        ct = B.get("hunk_details", {}).get("content", [])
        if ct:
            P("")
            P("**Content hunks (must be resolved):**")
            for s in ct[:20]:
                P(f"- src L{s['src_line']} / dst L{s['dst_line']}: `{s['removed'][:80]}` -> `{s['added'][:80]}`")
        pk = ck.get("packages") or {}
        P("")
        P(f"Preamble packages dropped: {pk.get('dropped') or 'none'}; added: {pk.get('added') or 'none'}.")
    else:
        P("body_diff: not run.")
    P("")

    # ---------------- rules applied ----------------------------------------------
    if R:
        P("## Mechanical rewrites (make_rules -> migrate_tex)")
        for op in R.get("ops", []):
            head = {k: v for k, v in op.items() if k not in ("why", "text")}
            P(f"- `{json.dumps(head, ensure_ascii=False)}`" + (f" -- {op['why']}" if op.get("why") else ""))
        for nline in R.get("notes", []):
            P(f"- note: {nline}")
        P("")

    # ---------------- layout ------------------------------------------------------
    P("## Layout pass (layout_figures)")
    if L:
        sg, dg = L.get("src_geometry", {}), L.get("dst_geometry", {})
        P(f"Source geometry: text {sg.get('text_width_in')} in, column {sg.get('column_width_in')} in ({sg.get('columns')} col). Target: text {dg.get('text_width_in')} in ({dg.get('columns')} col). Physical widths preserved unless stated.")
        P("")
        P("| # | Graphic | Source context | Action |")
        P("|---|---|---|---|")
        for r in L.get("rows", []):
            ctx = (r.get("src_float") or "-") + (f" > {r['src_container']}" if r.get("src_container") else "")
            P(f"| {r['idx']} | `{r['file']}` | {ctx} | {r['action']} |")
        for p in L.get("pairs", []):
            if p.get("status") == "paired":
                P(f"- Combined {p.get('items', p['labels'])} into one {p.get('env', 'float')} ({p.get('mode')}) -> widths {[fmt_frac(f) for f in p['fracs']]} of the line"
                  + (f" (scaled by {p['scaled_by']})" if p.get("scaled_by", 1) < 1 else "")
                  + ("; one block split into sub-boxes" if p.get("same_block") else "; the later block moved next to the earlier one")
                  + ("; original caption texts verbatim after \\subref markers, labels kept, references render as 3a/3b" if p.get("mode") == "subfloats" else "") + ".")
            elif p.get("status") == "refused":
                P(f"- Not paired {p['labels']}: {p.get('reason')}")
        for w in L.get("wraps", []):
            if w.get("status") == "wrapped":
                P(f"- Wrapped `{w['label']}` as `{w['env']}{{{w['side']}}}{{{fmt_frac(w['frac'])}\\linewidth}}`: box needs ~{w['need_lines']} lines, anchor paragraph offers ~{w['capacity_lines']} ({w['anchor_words']} words): \"{w['anchor_preview'][:60]}...\"")
            elif w.get("status") == "refused":
                P(f"- Not wrapped `{w['label']}`: {w.get('reason')}")
        tc = L.get("table_captions") or {}
        if tc.get("moved"):
            P(f"- {tc['moved']} table caption(s) moved {tc['where']} the tabular material.")
        if L.get("placement"):
            P(f"- {L['placement']} figure placement specifier(s) normalised.")
    else:
        P("layout_figures: not run.")
    P("")

    # ---------------- compile --------------------------------------------------------
    P("## Compile (local sandbox)")
    if C:
        if C.get("status") == "compiled":
            P(f"{C.get('engine')}: {C.get('pages')} pages; references start on page {C.get('references_page')}; appendix starts on page {C.get('appendix_page')}; "
              f"overfull hbox {C.get('overfull_hbox')} (worst {C.get('worst_overfull_pt')}); undefined refs {C.get('undefined_refs')}, cites {C.get('undefined_cites')}; wrapfig warnings {C.get('wrapfig_warnings')}.")
            P("Overleaf compiles with pdfLaTeX by default; line breaks and the exact page count may differ slightly. Treat the Overleaf result as authoritative.")
        else:
            P(f"{C.get('engine')}: COMPILE FAILED -- see the build log.")
    else:
        P("compile_check: not run (no TeX engine, or skipped). Compile on Overleaf.")
    P("")

    # ---------------- rule check -------------------------------------------------------
    P(f"## Rule check against {dname} ({args.stage.replace('_', '-')})")
    if K:
        P("")
        P("| Rule | Status | Detail | Source |")
        P("|---|---|---|---|")
        for c in K["checks"]:
            P(f"| {c['rule']} | {c['status']} | {c['detail'].replace('|', '/')} | {str(c.get('source', '')).replace('|', '/')[:90]} |")
        s = K["summary"]
        P("")
        P(f"Summary: FAIL {s.get('FAIL', 0)}, author action {s.get('author action', 0)}, info {s.get('info', 0)}, pass {s.get('pass', 0)}, n/a {s.get('n/a', 0)}."
          + ("" if not s.get("FAIL") else " **Format conflicts remain; the migration is not finished.**"))
    else:
        P("check_compliance: not run.")
    P("")

    # ---------------- pre-existing --------------------------------------------------------
    pre = list(args.preexisting)
    if B:
        pre += [f"body_diff: {r}" for r in B.get("reviews", []) if "pre-existing" in r or "not found in source" in r]
        pre += [f"body_diff: {w}" for w in B.get("warnings", [])]
    if L:
        pre += [f"layout: `{r['file']}` {r['action']}" for r in L.get("rows", []) if "left unchanged" in str(r.get("action", ""))]
    P("## Pre-existing issues in the source (reported, not fixed unless stated)")
    if pre:
        for x in pre:
            P(f"- {x}")
    else:
        P("- none noticed")
    P("")
    P("## Not done (by policy)")
    P("- No text written, moved, shortened or padded: required statements get a `% TODO` comment only; the page count is reported, not chased.")
    P("- No figure redrawn, no table split or reformatted beyond width scaling; the `.bib` and all graphics are byte-identical.")
    for nline in args.note:
        P(f"- {nline}")
    P("")
    P("## Deliverables")
    for d in args.deliverable:
        P(f"- `{d}`")
    P("- `body_diff.json`, `layout.json`, `compliance.json`, `compile.json`, this report")
    Path(args.out).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"make_report: wrote {args.out} ({len(out)} lines; {n} author to-do item(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
